name: ForeverYoung
version: '${version}'
main: joshdev.foreveryoung.ForeverYoung
api-version: '1.21'
commands:
  babify:
    description: Babify an animal.
    usage: /babify
    permission: foreveryoung.babify
  debabify:
    description: Debabify an animal.
    usage: /debabify
    permission: foreveryoung.debabify